classdef ScanImageParameterParsingTest < matlab.unittest.TestCase
%ScanImageParameterParsingTest Parsing of ScanImage header values
%
%   Tests nansen.module.twophoton.io.scanimage.getParameterValueFromString,
%   which turns one "SI.name = value" metadata line into a MATLAB value
%   without evaluating the text. The cases are the literal forms
%   ScanImage writes: numbers, strings, logicals, bracketed arrays, cell
%   arrays and size constructors.
%
%   Run tests:
%       runtests('twophotontest.ScanImageParameterParsingTest')

    properties (TestParameter)
        Literal = struct( ...
            'integer', struct('text', 'SI.hRoiManager.linesPerFrame = 512', 'expected', 512), ...
            'decimal', struct('text', 'SI.hRoiManager.scanZoomFactor = 1.5', 'expected', 1.5), ...
            'exponent', struct('text', 'SI.hScan2D.linePeriod = 6.3e-05', 'expected', 6.3e-05), ...
            'negative', struct('text', 'SI.hMotors.motorPosition = -12.5', 'expected', -12.5), ...
            'nanValue', struct('text', 'SI.hBeams.powers = NaN', 'expected', NaN), ...
            'infValue', struct('text', 'SI.x = -Inf', 'expected', -Inf), ...
            'string', struct('text', 'SI.hScan2D.scannerType = ''Resonant''', 'expected', 'Resonant'), ...
            'numericString', struct('text', 'SI.VERSION_MAJOR = ''2019''', 'expected', '2019'), ...
            'escapedQuote', struct('text', 'SI.note = ''it''''s''', 'expected', 'it''s'), ...
            'trueValue', struct('text', 'SI.hChannels.loggingEnable = true', 'expected', true), ...
            'falseValue', struct('text', 'SI.hFastZ.enable = false', 'expected', false), ...
            'emptyBrackets', struct('text', 'SI.hStackManager.zs = []', 'expected', []), ...
            'rowVector', struct('text', 'SI.hMotors.motorPosition = [0 0 0]', 'expected', [0 0 0]), ...
            'columnVector', struct('text', 'SI.hChannels.channelSave = [1;2]', 'expected', [1; 2]), ...
            'matrix', struct('text', 'SI.m = [1 2; 3 4]', 'expected', [1 2; 3 4]), ...
            'commaSeparated', struct('text', 'SI.v = [1, 2, 3]', 'expected', [1 2 3]), ...
            'logicalArray', struct('text', 'SI.hChannels.channelAdcResolution = [true false]', 'expected', [true false]), ...
            'nanArray', struct('text', 'SI.p = [NaN NaN]', 'expected', [NaN NaN]), ...
            'cellOfStrings', struct('text', 'SI.hChannels.channelMergeColor = {''green'' ''red''}', 'expected', {{'green', 'red'}}), ...
            'cellOfArrays', struct('text', 'SI.hChannels.channelLUT = {[0 100] [0 200]}', 'expected', {{[0 100], [0 200]}}), ...
            'emptyCell', struct('text', 'SI.c = {}', 'expected', {{}}), ...
            'zerosConstructor', struct('text', 'SI.hDisplay.selectedZs = zeros(1,0)', 'expected', zeros(1, 0)), ...
            'onesConstructor', struct('text', 'SI.o = ones(2, 1)', 'expected', ones(2, 1)), ...
            'nanConstructor', struct('text', 'SI.n = nan(1,3)', 'expected', nan(1, 3)), ...
            'trueConstructor', struct('text', 'SI.t = true(1,0)', 'expected', true(1, 0)))
    end

    methods (Access = private)
        function value = parse(~, text)
            value = nansen.module.twophoton.io.scanimage.getParameterValueFromString(text);
        end
    end

    methods (Test)

        function testLiteralIsParsed(testCase, Literal)
            value = testCase.parse(Literal.text);
            testCase.verifyEqual(value, Literal.expected)
            testCase.verifyClass(value, class(Literal.expected))
        end

        function testUnknownSyntaxIsReturnedAsTextWithAWarning(testCase)
            % Header text must never be executed, so an expression that
            % is not a literal comes back verbatim instead of being run.
            value = testCase.verifyWarning( ...
                @() testCase.parse('SI.weird = someFunction(1)'), ...
                'NANSEN:TwoPhoton:ScanImage:UnparsedParameterValue');
            testCase.verifyEqual(value, 'someFunction(1)')
        end

        function testUnbalancedBracketsAreReturnedAsText(testCase)
            value = testCase.verifyWarning(@() testCase.parse('SI.x = [1 2'), ...
                'NANSEN:TwoPhoton:ScanImage:UnparsedParameterValue');
            testCase.verifyEqual(value, '[1 2')
        end

        function testEmptyValueWarnsAndReturnsEmpty(testCase)
            value = testCase.verifyWarning(@() testCase.parse('SI.x = '), ...
                'NANSEN:TwoPhoton:ScanImage:EmptyParameterValue');
            testCase.verifyEmpty(value)
        end

        function testValueMayContainAnEqualsSign(testCase)
            value = testCase.parse('SI.expr = ''a=b''');
            testCase.verifyEqual(value, 'a=b')
        end

        function testLineWithoutSeparatorErrors(testCase)
            testCase.verifyError(@() testCase.parse('SI.x'), ...
                'NANSEN:TwoPhoton:ScanImage:InvalidParameterString')
        end
    end
end
